---
- name: update and upgrade
  apt:
    name: "*"
    state: "latest"
    force_apt_get: true

- name: autoremove unnecesary packages
  apt:
    autoremove: yes
    purge: yes

- name: reboot required?
  stat:
    path: /var/run/reboot-required
  register: yesReboot

- name: reboot machine
  command: /sbin/reboot
  when: yesReboot.stat.exists 
