---
- name: remove older versions of Docker
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: ensure dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Docker GPG key
  apt_key: url=https://download.docker.com/linux/debian/gpg

- name: Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian/ {{ ansible_distribution_release }} stable
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name: "docker-ce"
    update_cache: yes
    state: present
